### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by ozanyolyapar** [thelastguardian/tplinkexporter#4]
I am using your docker image in my home network monitoring "stack" and got already multiple times ram usage warnings. 

![Screenshot from 2021-03-12 13-33-49](https://user-images.githubusercontent.com/12610841/110942430-18a8f580-833a-11eb-9ec8-8e7c51e397e4.png)
Here you can see the ram usage of the last 8 days. If you need additional info, just ask.

**Comment by thelastguardian** [comment]
Hi, thanks for the report. Should be fixed in #5. Let me know if you continue to see this with the updated docker image (thelastguardian/tplinkexporter:latest @ sha256:9daf3ef13b464783707f082807301c9c1adaa36964813458664f3e6cb17ac837). I'll leave this issue open for a few days as well, to confirm on my own memory usage graphs.

**Comment by thelastguardian** [comment]
I can confirm the memory leak has been fixed, closing.
